src/Entity/Horaire.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\HoraireRepository")
 */
class Horaire
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Destination", inversedBy="horaires_departure")
     * @ORM\JoinColumn(nullable=false)
     */
    private $from;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Destination", inversedBy="horaires_arrival")
     * @ORM\JoinColumn(nullable=false)
     */
    private $to;

    /**
     * @ORM\Column(type="datetime")
     */
    private $day;

    /**
     * @ORM\Column(type="time")
     */
    private $depart_at;

    /**
     * @ORM\Column(type="time")
     */
    private $arrive_at;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Place", mappedBy="horaire_id", orphanRemoval=true)
     */
    private $places;

    public function __construct()
    {
        $this->places = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFrom(): ?Destination
    {
        return $this->from;
    }

    public function setFrom(?Destination $from): self
    {
        $this->from = $from;

        return $this;
    }

    public function getTo(): ?Destination
    {
        return $this->to;
    }

    public function setTo(?Destination $to): self
    {
        $this->to = $to;

        return $this;
    }

    public function getDay(): ?\DateTimeInterface
    {
        return $this->day;
    }

    public function setDay(\DateTimeInterface $day): self
    {
        $this->day = $day;

        return $this;
    }

    public function getDepartAt(): ?\DateTimeInterface
    {
        return $this->depart_at;
    }

    public function setDepartAt(\DateTimeInterface $depart_at): self
    {
        $this->depart_at = $depart_at;

        return $this;
    }

    public function getArriveAt(): ?\DateTimeInterface
    {
        return $this->arrive_at;
    }

    public function setArriveAt(\DateTimeInterface $arrive_at): self
    {
        $this->arrive_at = $arrive_at;

        return $this;
    }

    /**
     * @return Collection|Place[]
     */
    public function getPlaces(): Collection
    {
        return $this->places;
    }

    public function addPlace(Place $place): self
    {
        if (!$this->places->contains($place)) {
            $this->places[] = $place;
            $place->setHoraireId($this);
        }

        return $this;
    }

    public function removePlace(Place $place): self
    {
        if ($this->places->contains($place)) {
            $this->places->removeElement($place);
            // set the owning side to null (unless already changed)
            if ($place->getHoraireId() === $this) {
                $place->setHoraireId(null);
            }
        }

        return $this;
    }
}

src/Controller/SearchPlaceController.php
<?php

namespace App\Controller;

use App\Entity\Horaire;
use App\Entity\Place;
use App\Form\SearchFormType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;

class SearchPlaceController extends AbstractController
{
    /**
     * @Route("/search/place", name="search_place")
     * @Method({"GET", "POST"})
     */
    public function index(Request $request)
    {
        $form = $this->createForm(SearchFormType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $fromPlace = $form->getData()["departure"];
            $toPlace = $form->getData()["destination"];
            $beginningAtTime = $form->getData()["from_time"];

            $results = $this->getDoctrine()
                ->getRepository(Horaire::class)
                ->findFromToBeginningAt($fromPlace, $toPlace, $beginningAtTime);

            return $this->render('search_place/result.html.twig', [
                'controller_name' => 'SearchPlaceController',
                'results' => $results,
            ]);
        }
        return $this->render('search_place/index.html.twig', [
            'controller_name' => 'SearchPlaceController',
            'form' => $form->createView(),
        ]);
    }
}

templates/search_place/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
</div>
{% endblock %}

templates/search_place/result.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>

    <ul>
        {% for result in results %}
            <li>
                {% for horaire in result %}
                    <p>
                        [ départ : {{ horaire.from.name }} à {{ horaire.departAt|date("g:ia") }} le {{ horaire.day|date("d/m") }}
                        , arrivée : {{ horaire.to.name }} à {{ horaire.arriveAt|date("g:ia") }}  le {{ horaire.day|date("d/m") }}]
                    </p>
                    <br>
                {% endfor %}
            </li>
        {% endfor %}
    </ul>
{% endblock %}